version: '3.8'

services:
  tunlink_postgres: # Needs updating
    image: postgres:alpine
    container_name: tunlink_postgres # Needs updating
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - tunlink_postgres_data:/var/lib/postgresql/data # Needs updating

  tunlink_redis: # Needs updating
    image: redis:alpine
    container_name: tunlink_redis # Needs updating
    ports:
      - '6379:6379'
    volumes:
      - tunlink_redis_data:/data # Needs updating

networks:
  default:
    name: tunlink_network # Needs updating

volumes:
  tunlink_postgres_data: # Needs updating
  tunlink_redis_data: # Needs updating

